#!/usr/bin/env ruby

require "fileutils"

THIS_DIR = File.expand_path("..", __FILE__)
VERSION = "2023.1"

if `uname -s`.strip == "Darwin"
  CONFIGS = {
    "~/Library/Application\ Support/JetBrains/IdeaIC#{VERSION}" => THIS_DIR,
    "~/Library/Application\ Support/JetBrains/IntelliJIdea#{VERSION}" => THIS_DIR,
  }
else
  CONFIGS = {
  "~/.config/JetBrains/IdeaIC#{VERSION}" => THIS_DIR,
  "~/.local/share/JetBrains/IdeaIC#{VERSION}" => "#{THIS_DIR}/plugins",
  }
end

def main
  CONFIGS.each do |source, destination|
    source = File.expand_path(source)
    destination = File.expand_path(destination)
    if File.exist?(source)
      backup = "#{source}.backup.#{Time.now.strftime("%Y%m%d%H%M%S")}"
      puts "Backing up #{source} to #{backup}"
      FileUtils.cp_r(source, backup)
    end

    FileUtils.mkdir_p(File.dirname(source))
    FileUtils.rm_rf(source)
    FileUtils.ln_s(destination, source)
  end
end

main if __FILE__ == $0
